In [4]:
import sys
sys.path.append("..")

import os
from os.path import join, splitext

import pandas as pd
from src.db import *
from src.config import *

In [16]:
def reading_tables():
    table_names = os.listdir(SaveConfig.OUT_DIR)
    tables_dict = dict()
    for name in table_names:
        tables_dict[splitext(name)[0]] = pd.read_csv(join(SaveConfig.OUT_DIR, name))
    return tables_dict

In [23]:
tables_dict = reading_tables()

In [24]:
tables_dict.keys()

dict_keys(['pipeline_table', 'truck_table', 'path_table', 'machine_table'])

In [25]:
pipeline_table = tables_dict["pipeline_table"]
machine_table = tables_dict["machine_table"]

In [26]:
machine_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031316 entries, 0 to 1031315
Data columns (total 8 columns):
equipment_id       1031316 non-null object
parcel_id          1031316 non-null int64
small_id           1031316 non-null int64
parcel_type        1031316 non-null object
time_stamp         1031316 non-null float64
action             1031316 non-null object
real_time_stamp    1031316 non-null object
run_time           1031316 non-null object
dtypes: float64(1), int64(2), object(5)
memory usage: 62.9+ MB

In [29]:
machine_table.drop_duplicates().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123137 entries, 0 to 156710
Data columns (total 8 columns):
equipment_id       123137 non-null object
parcel_id          123137 non-null int64
small_id           123137 non-null int64
parcel_type        123137 non-null object
time_stamp         123137 non-null float64
action             123137 non-null object
real_time_stamp    123137 non-null object
run_time           123137 non-null object
dtypes: float64(1), int64(2), object(5)
memory usage: 8.5+ MB

In [27]:
len(machine_table.small_id.unique())

4767

In [28]:
machine_table.drop_duplicates().shape

(123137, 8)

In [13]:
machine_table.head(100)

,equipment_id,parcel_id,small_id,parcel_type,time_stamp,action,real_time_stamp,run_time
0,r5_2,877496,877496,parcel,5803.000,wait,2017-08-15 22:36:43.000,2017-09-04 09:54:03.563210
1,r5_2,877496,877496,parcel,5806.130,start,2017-08-15 22:36:46.130,2017-09-04 09:54:03.563210
2,r5_2,877496,877496,parcel,5809.260,end,2017-08-15 22:36:49.260,2017-09-04 09:54:03.563210
3,m3_1,877496,877496,parcel,5867.170,wait,2017-08-15 22:37:47.170,2017-09-04 09:54:03.563210
4,m3_1,877496,877496,parcel,5867.170,start,2017-08-15 22:37:47.170,2017-09-04 09:54:03.563210
5,m3_1,877496,877496,parcel,5870.170,end,2017-08-15 22:37:50.170,2017-09-04 09:54:03.563210
6,j15_1,877496,877496,parcel,6083.210,wait,2017-08-15 22:41:23.210,2017-09-04 09:54:03.563210
7,j15_1,877496,877496,parcel,6083.210,start,2017-08-15 22:41:23.210,2017-09-04 09:54:03.563210
8,j15_1,877496,877496,parcel,6087.975,end,2017-08-15 22:41:27.975,2017-09-04 09:54:03.563210
9,i22_3,877496,877496,parcel,6228.805,wait,2017-08-15 22:43:48.805,2017-09-04 09:54:03.563210
10,i22_3,877496,877496,parcel,6228.805,start,2017-08-15 22:43:48.805,2017-09-04 09:54:03.563210
11,i22_3,877496,877496,parcel,6229.125,end,2017-08-15 22:43:49.125,2017-09-04 09:54:03.563210
12,i21_1,877496,877496,parcel,6307.195,wait,2017-08-15 22:45:07.195,2017-09-04 09:54:03.563210
13,i21_1,877496,877496,parcel,6307.195,start,2017-08-15 22:45:07.195,2017-09-04 09:54:03.563210
14,i21_1,877496,877496,parcel,6307.515,end,2017-08-15 22:45:07.515,2017-09-04 09:54:03.563210
15,c13_10,877496,877496,parcel,6363.715,wait,2017-08-15 22:46:03.715,2017-09-04 09:54:03.563210
16,r3_2,869159,869159,parcel,9906.000,wait,2017-08-15 23:45:06.000,2017-09-04 09:54:03.563210
17,r3_2,869159,869159,parcel,9915.390,start,2017-08-15 23:45:15.390,2017-09-04 09:54:03.563210
18,r3_2,869159,869159,parcel,9918.520,end,2017-08-15 23:45:18.520,2017-09-04 09:54:03.563210
19,m2_1,869159,869159,parcel,9976.430,wait,2017-08-15 23:46:16.430,2017-09-04 09:54:03.563210
20,m2_1,869159,869159,parcel,9976.430,start,2017-08-15 23:46:16.430,2017-09-04 09:54:03.563210
21,m2_1,869159,869159,parcel,9979.430,end,2017-08-15 23:46:19.430,2017-09-04 09:54:03.563210
22,j10_1,869159,869159,parcel,10121.060,wait,2017-08-15 23:48:41.060,2017-09-04 09:54:03.563210
23,j10_1,869159,869159,parcel,10121.060,start,2017-08-15 23:48:41.060,2017-09-04 09:54:03.563210
24,j10_1,869159,869159,parcel,10125.825,end,2017-08-15 23:48:45.825,2017-09-04 09:54:03.563210
25,i19_3,869159,869159,parcel,10242.055,wait,2017-08-15 23:50:42.055,2017-09-04 09:54:03.563210
26,i19_3,869159,869159,parcel,10242.055,start,2017-08-15 23:50:42.055,2017-09-04 09:54:03.563210
27,i19_3,869159,869159,parcel,10242.375,end,2017-08-15 23:50:42.375,2017-09-04 09:54:03.563210
28,c13_10,869159,869159,parcel,10358.255,wait,2017-08-15 23:52:38.255,2017-09-04 09:54:03.563210
29,r5_1,902167,902167,parcel,9965.000,wait,2017-08-15 23:46:05.000,2017-09-04 09:54:03.563210
...,...,...,...,...,...,...,...,...
70,c13_13,795035,795035,parcel,16812.450,wait,2017-08-16 01:40:12.450,2017-09-04 09:54:03.563210
71,r4_9,847332,847332,parcel,10986.000,wait,2017-08-16 00:03:06.000,2017-09-04 09:54:03.563210
72,r4_9,847332,847332,parcel,10998.520,start,2017-08-16 00:03:18.520,2017-09-04 09:54:03.563210
73,r4_9,847332,847332,parcel,11001.650,end,2017-08-16 00:03:21.650,2017-09-04 09:54:03.563210
74,m2_10,847332,847332,parcel,11059.560,wait,2017-08-16 00:04:19.560,2017-09-04 09:54:03.563210
75,m2_10,847332,847332,parcel,11059.560,start,2017-08-16 00:04:19.560,2017-09-04 09:54:03.563210
76,m2_10,847332,847332,parcel,11062.560,end,2017-08-16 00:04:22.560,2017-09-04 09:54:03.563210
77,j15_1,847332,847332,parcel,11374.690,wait,2017-08-16 00:09:34.690,2017-09-04 09:54:03.563210
78,j15_1,847332,847332,parcel,11374.690,start,2017-08-16 00:09:34.690,2017-09-04 09:54:03.563210
79,j15_1,847332,847332,parcel,11379.455,end,2017-08-16 00:09:39.455,2017-09-04 09:54:03.563210
80,i22_3,847332,847332,parcel,11520.285,wait,2017-08-16 00:12:00.285,2017-09-04 09:54:03.563210
81,i22_3,847332,847332,parcel,11520.285,start,2017-08-16 00:12:00.285,2017-09-04 09:54:03.563210
82,i22_3,847332,847332,parcel,11520.605,end,2017-08-16 00:12:00.605,2017-09-04 09:54:03.563210
83,i21_2,847332,847332,parcel,11598.675,wait,2017-08-16 00:13:18.675,2017-09-04 09:54:03.563210
84,i21_2,847332,847332,parcel,11598.675,start,2017-08-16 00:13:18.675,2017-09-04 09:54:03.563210
85,i21_2,847332,847332,parcel,11598.995,end,2017-08-16 00:13:18.995,2017-09-04 09:54:03.563210
86,c13_14,847332,847332,parcel,11655.195,wait,2017-08-16 00:14:15.195,2017-09-04 09:54:03.563210
87,r4_9,909242,909242,parcel,10986.000,wait,2017-08-16 00:03:06.000,2017-09-04 09:54:03.563210
88,r4_9,909242,909242,parcel,11001.650,start,2017-08-16 00:03:21.650,2017-09-04 09:54:03.563210
89,r4_9,909242,909242,parcel,11004.780,end,2017-08-16 00:03:24.780,2017-09-04 09:54:03.563210
90,m2_10,909242,909242,parcel,11062.690,wait,2017-08-16 00:04:22.690,2017-09-04 09:54:03.563210
91,m2_10,909242,909242,parcel,11062.690,start,2017-08-16 00:04:22.690,2017-09-04 09:54:03.563210
92,m2_10,909242,909242,parcel,11065.690,end,2017-08-16 00:04:25.690,2017-09-04 09:54:03.563210
93,j21_1,909242,909242,parcel,11377.820,wait,2017-08-16 00:09:37.820,2017-09-04 09:54:03.563210
94,j21_1,909242,909242,parcel,11377.820,start,2017-08-16 00:09:37.820,2017-09-04 09:54:03.563210
95,j21_1,909242,909242,parcel,11382.585,end,2017-08-16 00:09:42.585,2017-09-04 09:54:03.563210
96,i17_1,909242,909242,parcel,11554.845,wait,2017-08-16 00:12:34.845,2017-09-04 09:54:03.563210
97,i17_1,909242,909242,parcel,11554.845,start,2017-08-16 00:12:34.845,2017-09-04 09:54:03.563210
98,i17_1,909242,909242,parcel,11555.165,end,2017-08-16 00:12:35.165,2017-09-04 09:54:03.563210
99,i20_2,909242,909242,parcel,11680.265,wait,2017-08-16 00:14:40.265,2017-09-04 09:54:03.563210

In [ ]:
machine_table.real_time_stamp = pd.to_datetime(machine_table.real_time_stamp)

In [ ]:
machine_table_wait = machine_table[machine_table.action == 'wait']
machine_table_start = machine_table[machine_table.action == 'start']

In [ ]:
machine_table_wait.head()

In [ ]:
def ret_time_series(table: pd.DataFrame):
    table_temp = table.groupby(['equipment_id', 'real_time_stamp'])['package_id'].value_counts()
    return table_temp.groupby('equipment_id').apply(lambda x: x.resample('s', level=1).sum()).fillna(0)

In [ ]:
table_wait = ret_time_series(machine_table_wait)
table_start = ret_time_series(machine_table_start)

In [ ]:
table_total = table_wait.sub(table_start, fill_value=0)
table_total = table_total.fillna(0)
table_final = table_total.groupby(level=0).cumsum()

In [ ]:
equipement_groups = table_final.groupby(level=0)

In [ ]:
table_r5_4 = equipement_groups.get_group('r5_4')
table_r5_1 = equipement_groups.get_group('r5_1')
table_r1_1 = equipement_groups.get_group('r1_1')

In [ ]:
b = equipement_groups.get_group('m1_1')

In [ ]:
%matplotlib inline

In [ ]:
table_r5_1.plot()

In [ ]:
table_r5_4.plot()

In [ ]:
table_r1_1.plot()

In [ ]:
table_m1_1.plot()